
spring:
  application:
    name: wogo
  datasource:
    url: "jdbc:mysql://localhost:3306/wogo_db"
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
        show_sql: true